/* SPDX-License-Identifier: GPL-2.0-only
 * Copyright (c) 2020, The Linux Foundation. All rights reserved. */

#ifndef _DT_BINDINGS_DISPLAY_MIPI_DSI_GENERIC_H
#define _DT_BINDINGS_DISPLAY_MIPI_DSI_GENERIC_H

#define MIPI_CMD_DCS_NOP			0x00
#define MIPI_CMD_DCS_SOFT_RESET			0x01
#define MIPI_CMD_DCS_ENTER_SLEEP_MODE		0x10
#define MIPI_CMD_DCS_EXIT_SLEEP_MODE		0x11
#define MIPI_CMD_DCS_ENTER_PARTIAL_MODE		0x12
#define MIPI_CMD_DCS_ENTER_NORMAL_MODE		0x13
#define MIPI_CMD_DCS_EXIT_INVERT_MODE		0x20
#define MIPI_CMD_DCS_ENTER_INVERT_MODE		0x21
#define MIPI_CMD_DCS_SET_GAMMA_CURVE		0x26
#define MIPI_CMD_DCS_SET_DISPLAY_OFF		0x28
#define MIPI_CMD_DCS_SET_DISPLAY_ON		0x29
#define MIPI_CMD_DCS_SET_COLUMN_ADDRESS		0x2A
#define MIPI_CMD_DCS_SET_PAGE_ADDRESS		0x2B
#define MIPI_CMD_DCS_WRITE_MEMORY_START		0x2C
#define MIPI_CMD_DCS_WRITE_LUT			0x2D
#define MIPI_CMD_DCS_READ_MEMORY_START		0x2E
#define MIPI_CMD_DCS_SET_PARTIAL_ROWS		0x30
#define MIPI_CMD_DCS_SET_PARTIAL_COLUMNS	0x31
#define MIPI_CMD_DCS_SET_SCROLL_AREA		0x33
#define MIPI_CMD_DCS_SET_TEAR_OFF		0x34
#define MIPI_CMD_DCS_SET_TEAR_ON		0x35
#define MIPI_CMD_DCS_SET_ADDRESS_MODE		0x36
#define MIPI_CMD_DCS_SET_SCROLL_START		0x37
#define MIPI_CMD_DCS_EXIT_IDLE_MODE		0x38
#define MIPI_CMD_DCS_ENTER_IDLE_MODE		0x39
#define MIPI_CMD_DCS_SET_PIXEL_FORMAT		0x3A
#define MIPI_CMD_DCS_WRITE_MEMORY_CONTINUE	0x3C
#define MIPI_CMD_DCS_SET_3D_CONTROL		0x3D
#define MIPI_CMD_DCS_READ_MEMORY_CONTINUE	0x3E
#define MIPI_CMD_DCS_SET_VSYNC_TIMING		0x40
#define MIPI_CMD_DCS_SET_TEAR_SCANLINE		0x44
#define MIPI_CMD_DCS_GET_SCANLINE		0x45
#define MIPI_CMD_DCS_SET_DISPLAY_BRIGHTNESS	0x51
#define MIPI_CMD_DCS_WRITE_CONTROL_DISPLAY	0x53
#define MIPI_CMD_DCS_WRITE_POWER_SAVE		0x55
#define MIPI_CMD_DCS_SET_CABC_MIN_BRIGHTNESS	0x5E
#define MIPI_CMD_DCS_READ_DDB_START		0xA1
#define MIPI_CMD_DCS_READ_PPS_START		0xA2
#define MIPI_CMD_DCS_READ_DDB_CONTINUE		0xA8
#define MIPI_CMD_DCS_READ_PPS_CONTINUE		0xA9

#define MIPI_GENERIC_DSI_MODE_VIDEO		(1 << 0)
#define MIPI_GENERIC_DSI_MODE_VIDEO_BURST	(1 << 1)
#define MIPI_GENERIC_DSI_MODE_VIDEO_SYNC_PULSE	(1 << 2)
#define MIPI_GENERIC_DSI_MODE_VIDEO_AUTO_VERT	(1 << 3)
#define MIPI_GENERIC_DSI_MODE_VIDEO_HSE		(1 << 4)
#define MIPI_GENERIC_DSI_MODE_VIDEO_HFP		(1 << 5)
#define MIPI_GENERIC_DSI_MODE_VIDEO_HBP		(1 << 6)
#define MIPI_GENERIC_DSI_MODE_VIDEO_HSA		(1 << 7)
#define MIPI_GENERIC_DSI_MODE_VSYNC_FLUSH	(1 << 8)
#define MIPI_GENERIC_DSI_MODE_EOT_PACKET	(1 << 9)
#define MIPI_GENERIC_DSI_CLOCK_NON_CONTINUOUS	(1 << 10)
#define MIPI_GENERIC_DSI_MODE_LPM		(1 << 11)

#define MIPI_GENERIC_DSI_FMT_RGB888		0
#define MIPI_GENERIC_DSI_FMT_RGB666		1
#define MIPI_GENERIC_DSI_FMT_RGB666_PACKED	2
#define MIPI_GENERIC_DSI_FMT_RGB565		3

#define MIPI_CMD_BEGIN_MARKER			0xcd
#define MIPI_CMD_END_MARKER			0xdc

#define MIPI_CMD_DELAY_MS(delay)		MIPI_CMD(1, 1, delay)
#define MIPI_CMD_GENERIC_WRITE(len, payload)	MIPI_CMD(2, len, payload)
#define MIPI_CMD_DCS_WRITE(len, payload)	MIPI_CMD(3, len, payload)
#define MIPI_CMD_TURN_ON_PERIPHERAL		MIPI_CMD(4, 0, )
#define MIPI_CMD_SHUTDOWN_PERIPHERAL		MIPI_CMD(5, 0, )
#define MIPI_CMD_BACKLIGHT_INIT			MIPI_CMD(6, 0, )

#define MIPI_CMD(code, len, payload)		/bits/ 8 <MIPI_CMD_BEGIN_MARKER code len payload MIPI_CMD_END_MARKER>

#endif /* _DT_BINDINGS_DISPLAY_MIPI_DSI_GENERIC_H */
